---
name: Grocy-ajlunis
version: 4.5.0.4.0
slug: grocy-ajlunis
description: ajlunis-tweaks ERP beyond your fridge! A groceries & household management solution for your home
url: https://github.com/ajlunis/addon-grocy
codenotary: codenotary@frenck.dev
ingress: true
ingress_stream: true
init: false
panel_title: Grocy
panel_icon: mdi:cart
panel_admin: true
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
  - ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
options:
  culture: en
  currency: USD
  entry_page: stock
  mode: "production"
  calendar_show_week_of_year: true
  energy_unit: "kcal"
  base_path: ""
  base_url: "/"
  stock_barcode_lookup_plugin: "OpenFoodFactsBarcodeLookupPlugin"
  disable_url_rewriting: false
  disable_auth: false
  auth_class: "Grocy\\Middleware\\DefaultAuthMiddleware"
  reverse_proxy_auth_header: "REMOTE_USER"
  reverse_proxy_auth_use_env: false
  ldap_address: ""
  ldap_base_dn: ""
  ldap_bind_dn: ""
  ldap_bind_pw: ""
  ldap_user_filter: ""
  ldap_uid_attr: ""
  default_permissions:
    - "ADMIN"
  grocycode_type: "2D"
  label_printer_webhook: ""
  label_printer_run_server: true
  label_printer_params: '{"font_family":"Source Sans Pro (Regular)"}'
  label_printer_hook_json: true
  tprinter_is_network_printer: false
  tprinter_print_quantity_name: true
  tprinter_print_notes: true
  tprinter_ip: "127.0.0.1"
  tprinter_port: 9100
  tprinter_connector: "/dev/usb/lp0"
  features:
    stock: true
    shoppinglist: true
    recipes: true
    chores: true
    tasks: true
    batteries: true
    equipment: true
    calendar: true
    label_printer: false
  tweaks:
    calendar_first_day_of_week: null
    chores_assignment: true
    meal_plan_first_day_of_week: null
    multiple_shopping_lists: true
    stock_best_before_date_tracking: true
    stock_location_tracking: true
    stock_price_tracking: true
    stock_product_freezing: true
    stock_product_opened_tracking: true
    stock_count_opened_products_against_minimum_stock_amount: true
    stock_best_before_date_field_number_pad: true
    recipes_mealplan: true
    thermal_printer: false
  feature_settings:
    disable_browser_barcode_camera_scanning: false
    auto_torch_on_with_camera: true
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  grocy_ingress_user: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  culture: list(ca|cs|da|de|el_GR|en|en_GB|es|et|fi|fr|he_IL|hu|it|ja|ko_KR|lt|nl|no|pl|pt_BR|pt_PT|ro|ru|sk_SK|sl|sv_SE|ta|tr|uk|zh_CN|zh_TW)
  currency: match(^[A-Z]{3}$)
  entry_page: list(stock|shoppinglist|recipes|chores|tasks|batteries|equipment|calendar|mealplan)
  mode: list(production|dev|demo|prerelease)
  calendar_show_week_of_year: bool
  energy_unit: str
  base_path: str
  base_url: str
  stock_barcode_lookup_plugin: str
  disable_url_rewriting: bool
  disable_auth: bool
  auth_class: str
  reverse_proxy_auth_header: str
  reverse_proxy_auth_use_env: bool
  ldap_address: str
  ldap_base_dn: str
  ldap_bind_dn: str
  ldap_bind_pw: str
  ldap_user_filter: str
  ldap_uid_attr: str
  default_permissions: [str]
  grocycode_type: list(1D|2D)
  label_printer_webhook: str
  label_printer_run_server: bool
  label_printer_params: str
  label_printer_hook_json: bool
  tprinter_is_network_printer: bool
  tprinter_print_quantity_name: bool
  tprinter_print_notes: bool
  tprinter_ip: str
  tprinter_port: port
  tprinter_connector: str
  features:
    schema:
      stock: bool
      shoppinglist: bool
      recipes: bool
      chores: bool
      tasks: bool
      batteries: bool
      equipment: bool
      calendar: bool
      label_printer: bool
  tweaks:
    schema:
      calendar_first_day_of_week: int(0,6)?
      chores_assignment: bool
      meal_plan_first_day_of_week: int(-1,6)?
      multiple_shopping_lists: bool
      stock_best_before_date_tracking: bool
      stock_location_tracking: bool
      stock_price_tracking: bool
      stock_product_freezing: bool
      stock_product_opened_tracking: bool
      stock_count_opened_products_against_minimum_stock_amount: bool
      stock_best_before_date_field_number_pad: bool
      recipes_mealplan: bool
      thermal_printer: bool
  feature_settings:
    schema:
      disable_browser_barcode_camera_scanning: bool
      auto_torch_on_with_camera: bool
  ssl: bool
  certfile: str
  keyfile: str
  grocy_ingress_user: str
