---
name: Grocy-ajlunis
version: 4.5.0.3.8
slug: grocy-ajlunis
description: ajlunis-tweaks ERP beyond your fridge! A groceries & household management solution for your home
url: https://github.com/ajlunis/addon-grocy
codenotary: codenotary@frenck.dev
ingress: true
ingress_stream: true
init: false
panel_title: Grocy
panel_icon: mdi:cart
panel_admin: true
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
  - ssl
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
options:
  culture: en
  currency: USD
  entry_page: stock
  mode: "production"
  calendar_show_week_of_year: true
  energy_unit: "kcal"
  base_path: ""
  base_url: "/"
  stock_barcode_lookup_plugin: "OpenFoodFactsBarcodeLookupPlugin"
  disable_url_rewriting: false
  disable_auth: false
  auth_class: "Grocy\\Middleware\\DefaultAuthMiddleware"
  reverse_proxy_auth_header: "REMOTE_USER"
  reverse_proxy_auth_use_env: false
  ldap_address: ""
  ldap_base_dn: ""
  ldap_bind_dn: ""
  ldap_bind_pw: ""
  ldap_user_filter: ""
  ldap_uid_attr: ""
  default_permissions:
    - "ADMIN"
  grocycode_type: "2D"
  label_printer_webhook: ""
  label_printer_run_server: true
  label_printer_params: '{"font_family":"Source Sans Pro (Regular)"}'
  label_printer_hook_json: true
  tprinter_is_network_printer: false
  tprinter_print_quantity_name: true
  tprinter_print_notes: true
  tprinter_ip: "127.0.0.1"
  tprinter_port: 9100
  tprinter_connector: "/dev/usb/lp0"
  features:
    stock: true
    shoppinglist: true
    recipes: true
    chores: true
    tasks: true
    batteries: true
    equipment: true
    calendar: true
    label_printer: false
  tweaks:
    calendar_first_day_of_week: null
    chores_assignment: true
    meal_plan_first_day_of_week: null
    multiple_shopping_lists: true
    stock_best_before_date_tracking: true
    stock_location_tracking: true
    stock_price_tracking: true
    stock_product_freezing: true
    stock_product_opened_tracking: true
    stock_count_opened_products_against_minimum_stock_amount: true
    stock_best_before_date_field_number_pad: true
    recipes_mealplan: true
    thermal_printer: false
  feature_settings:
    disable_browser_barcode_camera_scanning: false
    auto_torch_on_with_camera: true
  default_user_settings:
    night_mode: "follow-system"
    auto_night_mode_enabled: false
    auto_night_mode_time_range_from: "20:00"
    auto_night_mode_time_range_to: "07:00"
    auto_night_mode_time_range_goes_over_midnight: true
    night_mode_enabled_internal: false
    auto_reload_on_db_change: false
    show_clock_in_header: false
    keep_screen_on: false
    keep_screen_on_when_fullscreen_card: false
    product_presets_location_id: -1
    product_presets_product_group_id: -1
    product_presets_qu_id: -1
    product_presets_default_due_days: 0
    product_presets_treat_opened_as_out_of_stock: true
    product_presets_default_stock_label_type: 0
    stock_decimal_places_amounts: 4
    stock_decimal_places_prices_input: 2
    stock_decimal_places_prices_display: 2
    stock_auto_decimal_separator_prices: false
    stock_due_soon_days: 5
    stock_default_purchase_amount: 0
    stock_default_consume_amount: 1
    stock_default_consume_amount_use_quick_consume_amount: false
    scan_mode_consume_enabled: false
    scan_mode_purchase_enabled: false
    show_icon_on_stock_overview_page_when_product_is_on_shopping_list: true
    stock_overview_show_all_out_of_stock_products: false
    show_purchased_date_on_purchase: false
    show_warning_on_purchase_when_due_date_is_earlier_than_next: true
    shopping_list_to_stock_workflow_auto_submit_when_prefilled: false
    shopping_list_show_calendar: false
    shopping_list_round_up: false
    shopping_list_auto_add_below_min_stock_amount: false
    shopping_list_auto_add_below_min_stock_amount_list_id: 1
    shopping_list_print_show_header: true
    shopping_list_print_group_by_product_group: true
    shopping_list_print_layout_type: "table"
    recipe_ingredients_group_by_product_group: false
    recipes_show_list_side_by_side: true
    recipes_show_ingredient_checkbox: false
    chores_due_soon_days: 5
    chores_overview_swap_tracking_buttons: false
    batteries_due_soon_days: 5
    tasks_due_soon_days: 5
    calendar_color_products: "#007bff"
    calendar_color_tasks: "#28a745"
    calendar_color_chores: "#ffc107"
    calendar_color_batteries: "#17a2b8"
    calendar_color_meal_plan: "#6c757d"
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  grocy_ingress_user: ""
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
  culture: "list(ca|cs|da|de|el_GR|en|en_GB|es|et|fi|fr|he_IL|hu|it|ja|ko_KR|lt|nl|no|pl|pt_BR|pt_PT|ro|ru|sk_SK|sl|sv_SE|ta|tr|uk|zh_CN|zh_TW)?"
  currency: "match(^[A-Z]{3}$)?"
  entry_page: "list(stock|shoppinglist|recipes|chores|tasks|batteries|equipment|calendar|mealplan)?"
  mode: "list(production|dev|demo|prerelease)?"
  calendar_show_week_of_year: "bool?"
  energy_unit: "str?"
  base_path: "str?"
  base_url: "str?"
  stock_barcode_lookup_plugin: "str?"
  disable_url_rewriting: "bool?"
  disable_auth: "bool?"
  auth_class: "str?"
  reverse_proxy_auth_header: "str?"
  reverse_proxy_auth_use_env: "bool?"
  ldap_address: "str?"
  ldap_base_dn: "str?"
  ldap_bind_dn: "str?"
  ldap_bind_pw: "str?"
  ldap_user_filter: "str?"
  ldap_uid_attr: "str?"
  default_permissions: "[str]?"
  grocycode_type: "list(1D|2D)?"
  label_printer_webhook: "str?"
  label_printer_run_server: "bool?"
  label_printer_params: "str?"
  label_printer_hook_json: "bool?"
  tprinter_is_network_printer: "bool?"
  tprinter_print_quantity_name: "bool?"
  tprinter_print_notes: "bool?"
  tprinter_ip: "str?"
  tprinter_port: "port?"
  tprinter_connector: "str?"
  features:
    stock: "bool?"
    shoppinglist: "bool?"
    recipes: "bool?"
    chores: "bool?"
    tasks: "bool?"
    batteries: "bool?"
    equipment: "bool?"
    calendar: "bool?"
    label_printer: "bool?"
  tweaks:
    calendar_first_day_of_week: "int(0,6)?"
    chores_assignment: "bool?"
    meal_plan_first_day_of_week: "int(-1,6)?"
    multiple_shopping_lists: "bool?"
    stock_best_before_date_tracking: "bool?"
    stock_location_tracking: "bool?"
    stock_price_tracking: "bool?"
    stock_product_freezing: "bool?"
    stock_product_opened_tracking: "bool?"
    stock_count_opened_products_against_minimum_stock_amount: "bool?"
    stock_best_before_date_field_number_pad: "bool?"
    recipes_mealplan: "bool?"
    thermal_printer: "bool?"
  feature_settings:
    disable_browser_barcode_camera_scanning: "bool?"
    auto_torch_on_with_camera: "bool?"
  default_user_settings:
    night_mode: "str?"
    auto_night_mode_enabled: "bool?"
    auto_night_mode_time_range_from: "str?"
    auto_night_mode_time_range_to: "str?"
    auto_night_mode_time_range_goes_over_midnight: "bool?"
    night_mode_enabled_internal: "bool?"
    auto_reload_on_db_change: "bool?"
    show_clock_in_header: "bool?"
    keep_screen_on: "bool?"
    keep_screen_on_when_fullscreen_card: "bool?"
    product_presets_location_id: "int?"
    product_presets_product_group_id: "int?"
    product_presets_qu_id: "int?"
    product_presets_default_due_days: "int?"
    product_presets_treat_opened_as_out_of_stock: "bool?"
    product_presets_default_stock_label_type: "int?"
    stock_decimal_places_amounts: "int?"
    stock_decimal_places_prices_input: "int?"
    stock_decimal_places_prices_display: "int?"
    stock_auto_decimal_separator_prices: "bool?"
    stock_due_soon_days: "int?"
    stock_default_purchase_amount: "int?"
    stock_default_consume_amount: "int?"
    stock_default_consume_amount_use_quick_consume_amount: "bool?"
    scan_mode_consume_enabled: "bool?"
    scan_mode_purchase_enabled: "bool?"
    show_icon_on_stock_overview_page_when_product_is_on_shopping_list: "bool?"
    stock_overview_show_all_out_of_stock_products: "bool?"
    show_purchased_date_on_purchase: "bool?"
    show_warning_on_purchase_when_due_date_is_earlier_than_next: "bool?"
    shopping_list_to_stock_workflow_auto_submit_when_prefilled: "bool?"
    shopping_list_show_calendar: "bool?"
    shopping_list_round_up: "bool?"
    shopping_list_auto_add_below_min_stock_amount: "bool?"
    shopping_list_auto_add_below_min_stock_amount_list_id: "int?"
    shopping_list_print_show_header: "bool?"
    shopping_list_print_group_by_product_group: "bool?"
    shopping_list_print_layout_type: "str?"
    recipe_ingredients_group_by_product_group: "bool?"
    recipes_show_list_side_by_side: "bool?"
    recipes_show_ingredient_checkbox: "bool?"
    chores_due_soon_days: "int?"
    chores_overview_swap_tracking_buttons: "bool?"
    batteries_due_soon_days: "int?"
    tasks_due_soon_days: "int?"
    calendar_color_products: "str?"
    calendar_color_tasks: "str?"
    calendar_color_chores: "str?"
    calendar_color_batteries: "str?"
    calendar_color_meal_plan: "str?"
  ssl: "bool?"
  certfile: "str?"
  keyfile: "str?"
  grocy_ingress_user: "str?"
